package io.github.pimak.ntfy.logback;

import ch.qos.logback.core.spi.ContextAware;

import io.github.pimak.ntfy.core.Diagnostics;

/**
 * Routes the engine's {@link Diagnostics} callbacks onto a Logback {@link ContextAware}'s
 * StatusManager methods ({@code addInfo}/{@code addWarn}/{@code addError}). Because it never touches
 * an SLF4J {@code Logger}, no recursive {@code ILoggingEvent} can be generated by the engine's own
 * self-diagnostics, and no credential-bearing string is ever routed to a real logger.
 *
 * <p>Construct one per appender, handing it the appender itself (a {@code ContextAware}); the
 * StatusManager methods it forwards to are inherited (public) from {@code ContextAwareBase}.
 */
final class LogbackDiagnostics implements Diagnostics {

  private final ContextAware host;

  LogbackDiagnostics(ContextAware host) {
    this.host = host;
  }

  @Override
  public void info(String msg) {
    host.addInfo(msg);
  }

  @Override
  public void warn(String msg) {
    host.addWarn(msg);
  }

  @Override
  public void error(String msg, Throwable t) {
    host.addError(msg, t);
  }
}
