package io.github.pimak.ntfy.spring;

import static org.assertj.core.api.Assertions.assertThat;

import java.beans.Introspector;
import java.io.IOException;
import java.io.InputStream;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.stream.Collectors;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.springframework.boot.configurationmetadata.ConfigurationMetadataProperty;
import org.springframework.boot.configurationmetadata.ConfigurationMetadataRepositoryJsonBuilder;
import org.springframework.boot.configurationmetadata.ValueHint;
import org.springframework.boot.configurationmetadata.ValueProvider;

/**
 * Guards the IDE-completion contract of this starter: every {@code ntfy.*} key an application can
 * set must appear in the generated {@code META-INF/spring-configuration-metadata.json} with a
 * description, so completing {@code ntfy.} in {@code application.yml} explains each key instead of
 * listing bare names.
 *
 * <p>It asserts against the file this module really produces, read with the same parser IDEs use,
 * which makes it a check on the build as much as on the content: if
 * {@code spring-boot-configuration-processor} ever stops running — the silent failure mode that
 * classpath processor discovery has on JDK 23+ — there is no metadata file at all, and every test
 * here fails on the {@code @BeforeAll} with a message pointing at the cause. The expected key set
 * is derived reflectively from {@link NtfyProperties}, so a field added later without javadoc fails
 * here rather than shipping an undocumented key.
 */
class NtfyConfigurationMetadataTest {

  private static final String METADATA_RESOURCE = "META-INF/spring-configuration-metadata.json";

  private static Map<String, ConfigurationMetadataProperty> properties;

  @BeforeAll
  static void loadGeneratedMetadata() throws IOException, URISyntaxException {
    // Resolved from this module's own class output rather than through the classloader: every
    // Spring Boot jar ships a file under that same name, so a classpath lookup could silently
    // answer with somebody else's metadata instead of failing when ours is absent.
    Path metadata = moduleClassOutput().resolve(METADATA_RESOURCE);

    assertThat(Files.exists(metadata))
        .withFailMessage(
            """
            %s is missing from this module's class output.

            It is generated by spring-boot-configuration-processor at compile time. If it is \
            absent the processor did not run: check the annotationProcessorPaths entry on \
            maven-compiler-plugin in ntfy-spring-boot-starter/pom.xml. Declaring the processor \
            as a plain (optional) dependency is NOT enough — javac stopped discovering \
            classpath processors by default in JDK 23.\
            """,
            metadata)
        .isTrue();

    try (InputStream in = Files.newInputStream(metadata)) {
      properties = ConfigurationMetadataRepositoryJsonBuilder.create(in).build().getAllProperties();
    }
  }

  /** The directory the main classes of this module were compiled into (target/classes). */
  private static Path moduleClassOutput() throws URISyntaxException {
    return Path.of(NtfyProperties.class.getProtectionDomain().getCodeSource().getLocation().toURI());
  }

  /** The keys Spring can actually bind, derived from the setters rather than hard-coded. */
  private static Set<String> boundKeys() {
    return Arrays.stream(NtfyProperties.class.getDeclaredMethods())
        .filter(NtfyConfigurationMetadataTest::isSetter)
        .map(method -> "ntfy." + toKebabCase(Introspector.decapitalize(method.getName().substring(3))))
        .collect(Collectors.toCollection(TreeSet::new));
  }

  private static boolean isSetter(Method method) {
    return Modifier.isPublic(method.getModifiers())
        && !Modifier.isStatic(method.getModifiers())
        && method.getName().startsWith("set")
        && method.getParameterCount() == 1;
  }

  private static String toKebabCase(String camelCase) {
    return camelCase.replaceAll("([a-z0-9])([A-Z])", "$1-$2").toLowerCase(Locale.ROOT);
  }

  @Test
  void metadataIsGenerated() {
    // Sanity check on the derivation itself: a silently empty key set would make every other
    // assertion in this class vacuous.
    assertThat(boundKeys()).hasSize(24);
    assertThat(properties.keySet()).containsAll(boundKeys());
  }

  @Test
  void everyBoundKeyIsDescribed() {
    List<String> undescribed =
        boundKeys().stream()
            .filter(key -> properties.get(key) == null || isBlank(properties.get(key).getDescription()))
            .toList();

    assertThat(undescribed)
        .withFailMessage(
            """
            These ntfy.* keys reach the IDE without a description: %s

            Descriptions come from the javadoc on the NtfyProperties FIELD (the processor ignores \
            getter javadoc). Add one there.\
            """,
            undescribed)
        .isEmpty();
  }

  @Test
  void nonLiteralDurationDefaultsSurvive() {
    // Duration.ofSeconds(5) is not a literal the processor can read off the field, so these three
    // defaults come from additional-spring-configuration-metadata.json. The merge must keep them
    // AND the javadoc description — that combination is what this asserts.
    assertThat(properties.get("ntfy.connect-timeout").getDefaultValue()).isEqualTo("5s");
    assertThat(properties.get("ntfy.request-timeout").getDefaultValue()).isEqualTo("10s");
    assertThat(properties.get("ntfy.suppression-window").getDefaultValue()).isEqualTo("3m");
    assertThat(properties.get("ntfy.connect-timeout").getDescription()).contains("connect timeout");
  }

  @Test
  void literalDefaultsAreInferredFromTheFields() {
    assertThat(properties.get("ntfy.enabled").getDefaultValue()).isEqualTo(true);
    assertThat(properties.get("ntfy.async").getDefaultValue()).isEqualTo(true);
    assertThat(properties.get("ntfy.async-queue-capacity").getDefaultValue()).isEqualTo(1024);
    assertThat(properties.get("ntfy.error-priority").getDefaultValue()).isEqualTo("high");
  }

  @Test
  void priorityKeysSuggestTheNtfyPriorityScale() {
    for (String key : List.of("ntfy.error-priority", "ntfy.digest-priority")) {
      List<Object> suggested =
          properties.get(key).getHints().getValueHints().stream().map(ValueHint::getValue).toList();
      assertThat(suggested).containsExactly("min", "low", "default", "high", "urgent");
    }
  }

  @Test
  void excludedLoggersCompletesAgainstLoggerNames() {
    List<String> providers =
        properties.get("ntfy.excluded-loggers").getHints().getValueProviders().stream()
            .map(ValueProvider::getName)
            .toList();
    assertThat(providers).contains("logger-name");
  }

  private static boolean isBlank(String value) {
    return value == null || value.isBlank();
  }
}
